spring.application.name=demo

# Puerto del servidor para Render
server.port=${PORT:8080}

# Base de datos (deja la tuya, no la toques)
spring.datasource.url=jdbc:postgresql://dpg-daoqdfv40ujc7389dhqg-a.frankfurt-postgres.render.com:5432/asistencia_muv5?sslmode=require
spring.datasource.username=asistencia_muv5_user
spring.datasource.password=2vZOYrV3zPUCcTyXViBOWFLLMtAtLpOV
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ============================================================
# 🔐 USUARIO PARA EL LOGIN (Spring Security)
# ============================================================
spring.security.user.name=admin
spring.security.user.password=123456
spring.security.user.roles=ADMIN
